# Generated by Django 5.1.1 on 2024-09-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('asosiy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=10)),
                ('yosh', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('daraja', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magsitr', 'Magsitr'), ('Aspirant', 'Aspirant'), ('Dokotrant', 'Dokotrant')], default='Magsitr', max_length=50)),
                ('fan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fan')),
            ],
            options={
                'verbose_name': 'Ustoz',
                'verbose_name_plural': 'Ustozlar',
            },
        ),
        migrations.AddField(
            model_name='fan',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yonalish'),
        ),
    ]
